font_size 10.0
bold_font auto
italic_font auto
bold_italic_font auto

confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 0
window_margin 22


background #000000

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'nnoremap y "+y:q!<CR>' +'vnoremap y "+y:q!<CR>' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'set number relativenumber' +'$' -


background_opacity          0.6
cursor_trail                1
window_padding_width        0

include themes/noctalia.conf


font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font
italic_font JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font
