# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# you can choose themes from $HOME/.config/kitty/kitty-themes/

font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 1
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 0
window_margin 22


background #000000

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'nnoremap y "+y:q!<CR>' +'vnoremap y "+y:q!<CR>' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'set number relativenumber' +'$' -


include ./kitty-themes/ayu_mirage.conf
# cursor_line_background #2a2e3b
cursor #dddddd
foreground #dddddd
cursor_shape block
shell_integration no-cursor
cursor_blink_interval 1

font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font
italic_font JetBrainsMono Nerd Font
bold_italic_font JetBrainsMono Nerd Font
