# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131315)
$foreground = rgb(EBE7E5)
$color0 = rgb(3A3B3D)
$color1 = rgb(10131B)
$color2 = rgb(314055)
$color3 = rgb(425773)
$color4 = rgb(804749)
$color5 = rgb(883F7F)
$color6 = rgb(948C87)
$color7 = rgb(DAD5D1)
$color8 = rgb(999592)
$color9 = rgb(151924)
$color10 = rgb(425672)
$color11 = rgb(587499)
$color12 = rgb(AB5F61)
$color13 = rgb(B554A9)
$color14 = rgb(C6BBB4)
$color15 = rgb(DAD5D1)
