# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh
$livewallpaper=""
$wallDIR = $HOME/Pictures/wallpapers  # change path manually here if needed

### wallpaper stuff ###
exec-once = swww-daemon --format xrgb

# Apps
exec = sleep 1 && swww img "$wallDIR/Girl.png" --transition-type none
exec-once = /home/alex/applications/Vicinae.AppImage server
# exec-once = /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@
