# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

input {
    kb_layout = us,ru
    kb_variant = unieng, unirus
    kb_options = grp:win_space_toggle
}

# xkb_symbols {
#     include "pc+us+ru"
#     include "group(win_space_toggle)"
#
#     ...
# }
#
# xkb_compat {
#     include "complete"
# }

binds {
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors =  1 # change to 1 if want to disable
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps = false 
}
