# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hypr.land/configuring/core/rules/window-rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
windowrule = match:class ^(md\.obsidian\.Obsidian)$, workspace 4, fullscreen on
