exec-once = $HOME/.config/hypr/initial-boot.sh
$configs = $HOME/.config/hypr/configs # Default Configs directory path
$UserConfigs = $HOME/.config/hypr/UserConfigs # User Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds
source= $configs/Startup_Apps.conf 
source= $configs/ENVariables.conf # Environment variables (defaults)
source= $configs/Laptops.conf 
source= $configs/WindowRules.conf # Window Rules and Layer Rules (defaults)
source= $configs/SystemSettings.conf # Default config for hypr 
source= $configs/Defaults.conf # settings for User defaults apps
source= $HOME/.config/hypr/monitors.conf
source= $HOME/.config/hypr/workspaces.conf
source = /home/alex/.config/hypr/hyprland-gui.conf



