# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EBE7E5
background         #131315
cursor             #969EAB

active_tab_foreground     #131315
active_tab_background     #EBE7E5
inactive_tab_foreground   #EBE7E5
inactive_tab_background   #131315

active_border_color   #EBE7E5
inactive_border_color #131315
bell_border_color     #10131B

color0      #3A3B3D
color1		#10131B
color2		#314055
color3		#425773
color4		#804749
color5		#883F7F
color6		#948C87
color7		#DAD5D1
color8		#999592
color9		#151924
color10		#425672
color11		#587499
color12		#AB5F61
color13		#B554A9
color14		#C6BBB4
color15		#DAD5D1
