local scriptsDir = "~/.config/hypr/scripts"
local wallDIR =  "~/Pictures/wallpapers"

hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon --format xrgb")
    hl.exec_cmd(scriptsDir .. "/ChangeLayout.sh init")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("$HOME/.config/hypr/scripts/Dropterminal.sh kitty &")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("nm-tray")
    hl.exec_cmd("swaync")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(scriptsDir .. "/Hyprsunset.sh init")
    hl.exec_cmd("/home/alex/applications/Vicinae.AppImage server")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd(scriptsDir .. "/KeybindsLayoutInit.sh")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("sleep 1 && swww img \"$HOME/Pictures/wallpapers/Girl.png\" --transition-type none")
end)
